apiVersion: v1
kind: Service
metadata:
  name: ts-redis
  labels:
    app: redis
    tier: ts-redis
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    tier: ts-redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        tier: ts-redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
          - containerPort: 6379

